openapi: 3.0.1
info:
  description: The casing API is used to get details for casings
  version: 1.0.0
  title: Casing
  contact:
    email: theresa.reus@goodyear-dunlop.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'https://localhost:3000/'
    description: Local server
tags:
  - name: details
    description: Everything about your casing details
paths:
  /casingdetails:
    get:
      tags:
      - "details"
      summary: "Status handler"
      description: ""
      parameters:
        - in: query
          name: crnnumber
          required: true
          example: '12223456'
          schema:
            type: string
            minimum: 1
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CasingResponse"
          description: "Endpoint status check"
        500:
          description: "Internal Server error"
components:
  schemas:
    CasingResponse:
      type: "object"
      properties:
        result:
          type: string
          example: bf7f5254cd22318be47afe3e64b475a006c4774b
    