openapi: 3.0.1
info:
  description: The campaign API is used to get details for campaigns
  version: 1.0.0
  title: Campaign
  contact:
    email: tsimafei_dubavik@goodyear.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'https://localhost:3000/'
    description: Local server
tags:
  - name: campaigns
    description: Everything about your campaigns
paths:
  /campaign:
    get:
      tags:
      - "campaigns"
      summary: "Status handler"
      description: ""
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CampaignResponse"
          description: "OK"
        500:
          description: "Internal Server error"
components:
  schemas:
    CampaignResponse:
      type: "object"
      properties:
        CustomRejectReason:
          type: "string"
        ReasonReject:
          type: "string"
        agencyId:
          type: "string"
        brand:
          type: "string"
        brandRating:
          type: "string"
        bu:
          type: "string"
        campaignId:
          type: "string"
        campaignName:
          type: "string"
        campaignType:
          type: "string"
        chanceToWin:
          type: "string"
        dataUsageOptin:
          type: "boolean"
        dateParticipation:
          type: "string"
        feedback:
          type: "string"
        freeField1:
          type: "string"
        freeField2:
          type: "string"
        freeField3:
          type: "string"
        freeField4:
          type: "string"
        freeField5:
          type: "string"
        invoiceDate:
          type: "string"
        nationalIdentityNumber:
          type: "string"
        participateInPromotion:
          type: "boolean"
        preferredContactChannel:
          type: "string"
        promotionPlace:
          type: "string"
        promotionYear:
          type: "number"
        receiptInvoice:
          type: "string"
        season:
          type: "string"
        sendOn:
          type: "string"
        source:
          type: "string"
        status:
          type: "string"
        termsAccepted:
          type: "boolean"
        transactionRating:
          type: "string"
        typeInvoice:
          type: "string"
        voucherCode:
          type: "string"
        voucherType:
          type: "string"
        linkCampaign:
          required:
            - "PKey"
          properties:
            PKey:
              type: "string"
          type: "object"
