service: casingdetail-ms-lambda
provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1
  stage: stage
  timeout: 3
  environment:
    BUCKET: ${opt:stage, self:provider.stage}-casingdetail-ms-lambda-s3-deploy
    API_VERSION: v1
    STAGE: ${opt:stage, self:provider.stage}
    VERSION: ${opt:version, '1.0'}
    COMMIT_HASH: ${opt:commitHash, 'latest'}
    DEPLOY_TIME: ${opt:deployTime, ''}
  tracing: true # enable tracing
  usagePlan: {}
  iamRoleStatements:
    - Effect: "Allow" # xray permissions (required)
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
        - "s3:*"
        - "lambda:InvokeFunction"
      Resource:
        - "*"

plugins:
  - '@hewmen/serverless-plugin-typescript'
  - serverless-offline
  - serverless-plugin-warmup
  - serverless-plugin-warmup-ts-adapter
  - serverless-aws-documentation
  - serverless-reqvalidator-plugin
  - serverless-openapi-documentation
  - serverless-domain-manager
  - serverless-plugin-existing-s3
  - serverless-plugin-tracing
  - serverless-plugin-aws-alerts

package:
  individually: false
  excludeDevDependencies: true
  include:
  - src/**/!(*.spec).js
  exclude:
  - src/**/*.ts

functions:
  casingDetail:
    handler: src/casing/handler.casingDetails
    description: Casing Detail Handler
    events:
    - http:
        path: ${self:provider.environment.API_VERSION}/casingdetails
        method: get
        cors: true
        documentation: 
          summary: Returns the details of casing
          description: Returns the details of casing
          tags:
          - Casings
          methodResponses:
          - statusCode: '200'
            description: Returned when the operation is completed successfully.
            responseModels:
              "application/json": CasingResponse
          queryParams:
            - name: crnnumber
              description: 'todo'
custom:
  warmup:
    cleanFolder: false
    timeout: 30
    prewarm: true
    package:
      individually: false
    enabled:
      - staging
      - prod
  documentation:
    models:
    -
      name: CasingResponse
      contentType: "application/json"
      schema: ${file(openapi.yml):components.schemas.CasingResponse}

resources:
  Resources:
    ${file(./sls/${opt:stage, self:provider.stage}.yml):Resources}
